from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
ASSETS = BASE / "assets"

xlsx_file = ASSETS / "tmp.xlsx"


area_header = ["area_en", "area_ar"]
area_data_en = [
    "Nasr City",
    "Heliopolis",
    "New Cairo",
    "Maadi",
    "6th of October",
    "Sheikh Zayed",
    "Mohandessin",
    "Faisal",
    "Haram",
    "Dokki",
    "Zamalek",
    "Downtown",
    "New Cairo",
    "Al Rehab City",
    "Helwan",
    "Ain Shams",
    "Shoubra",
    "Hadayek El Ahram",
    "Al Mokatam",
    "Masaken Sheraton",
    "Obour",
    "Gesr El Suez",
    "Imbaba",
    "Giza",
    "Abbassiya",
    "Hadayek El Kobba",
    "Manial",
    "El Sayeda Zeinab",
    "El Shorouk City",
    "Madinaty",
    "Garden City",
    "El Azhar",
    "Agouza",
    "Smart Village",
    "Misr El Kadima",
    "Al Katameya",
    "Shoubra Al Khaimaa",
    "Alexandria Desert Road",
    "New Nozha",
    "October Gardens",
    "Cairo-Alex Highway",
    "Oraby",
    "Kerdasa",
    "New Cairo First Settlement",
    "New Cairo Banks",
    "El Mansoura",
    "Benha",
]

area_data_ar = [
    "مدينة نصر",
    "مصر الجديدة",
    "القاهرة الجديدة",
    "المعادي",
    "6 أكتوبر ",
    "شيخ زايد",
    "المهندسين",
    "فيصل",
    "الهرم",
    "الدقي",
    "الزمالك",
    "وسط البلد",
    "مصر الجديدة",
    "مدينة الرحاب",
    "حلوان",
    "عين شمس",
    "شبرا",
    "حدائق الأهرام",
    "المقطم",
    "مساكن شيراتون",
    "مدينة العبور",
    "جسر السويس",
    "امبابة",
    "الجيزة",
    "العباسية",
    "حدائق القبة",
    "المنيل",
    "السيدة زينب",
    "مدينة الشروق",
    "مدينتي",
    "جاردن سيتي",
    "الازهر",
    "العجوزة",
    "القرية الذكية",
    "مصر القديمة",
    "القطامية",
    "شبرا الخيمة",
    "طريق القاهرة اسكندرية الصحراوي",
    "النزهة الجديدة",
    "حدائق اكتوبر",
    "طريق القاهرة - اسكندرية",
    "عرابي",
    "كرداسة",
    "القاهرة الجديدة التجمع الاول",
    " القاهرة الجديدة البنوك",
    " المنصورة",
    " بنها",
]

area_data = [[area_data_en[i], area_data_ar[i]] for i in range(len(area_data_en))]

_area_data = [
    ["Nasr City", "مدينة نصر"],
    ["Heliopolis", "مصر الجديدة"],
    ["New Cairo", "القاهرة الجديدة"],
    ["Maadi", "المعادي"],
    ["6th of October", "6 أكتوبر "],
    ["Sheikh Zayed", "شيخ زايد"],
    ["Mohandessin", "المهندسين"],
    ["Faisal", "فيصل"],
    ["Haram", "الهرم"],
    ["Dokki", "الدقي"],
    ["Zamalek", "الزمالك"],
    ["Downtown", "وسط البلد"],
    ["New Cairo", "مصر الجديدة"],
    ["Al Rehab City", "مدينة الرحاب"],
    ["Helwan", "حلوان"],
    ["Ain Shams", "عين شمس"],
    ["Shoubra", "شبرا"],
    ["Hadayek El Ahram", "حدائق الأهرام"],
    ["Al Mokatam", "المقطم"],
    ["Masaken Sheraton", "مساكن شيراتون"],
    ["Obour", "مدينة العبور"],
    ["Gesr El Suez", "جسر السويس"],
    ["Imbaba", "امبابة"],
    ["Giza", "الجيزة"],
    ["Abbassiya", "العباسية"],
    ["Hadayek El Kobba", "حدائق القبة"],
    ["Manial", "المنيل"],
    ["El Sayeda Zeinab", "السيدة زينب"],
    ["El Shorouk City", "مدينة الشروق"],
    ["Madinaty", "مدينتي"],
    ["Garden City", "جاردن سيتي"],
    ["El Azhar", "الازهر"],
    ["Agouza", "العجوزة"],
    ["Smart Village", "القرية الذكية"],
    ["Misr El Kadima", "مصر القديمة"],
    ["Al Katameya", "القطامية"],
    ["Shoubra Al Khaimaa", "شبرا الخيمة"],
    ["Alexandria Desert Road", "طريق القاهرة اسكندرية الصحراوي"],
    ["New Nozha", "النزهة الجديدة"],
    ["October Gardens", "حدائق اكتوبر"],
    ["Cairo-Alex Highway", "طريق القاهرة - اسكندرية"],
    ["Oraby", "عرابي"],
    ["Kerdasa", "كرداسة"],
    ["New Cairo First Settlement", "القاهرة الجديدة التجمع الاول"],
    ["New Cairo Banks", " القاهرة الجديدة البنوك"],
    ["El Mansoura", " المنصورة"],
    ["Benha", " بنها"],
]
__all__ = [
    "xlsx_file",
    "area_header",
    "area_data",
    "area_data_en",
    "area_data_ar",
]
